GET http://localhost:5050/posts


####


GET http://localhost:5050/user/654793f40ee076ff8e428358


####


GET http://localhost:5050/company/654bc3e7b6f02f35c850eaf6


####


POST http://localhost:5050/user/create HTTP/1.1
Content-Type: application/json

{
   "firstname": "Alessandro",
   "lastname": "Orlandelli",
   "email": "orlaale@live.ji",
   "dateOfBirth": "29/09/2000",
   "password": "Ciaosnoale2909",
   "phoneNumber": "333444888999",
   "gender": "male"
}


####

POST http://localhost:5050/company/create HTTP/1.1
Content-Type: application/json

{
   "name": "prova",
   "email": "orlaale@live.com",
   "password": "Ciaosnoale2909",
   "phoneNumber": "333444888999"
}

####

POST http://localhost:5050/post/create/655126ae1305798bebc8a786 HTTP/1.1
Content-Type: application/json

{
   "year": "2002",
   "make": "Fiat",
   "model": "Panda",
   "engine": "1.1",
   "fuelType": "Benzina",
   "power": "40",
   "km": "140000",
   "description": "stoprovando la terza macchina come rivenditore",
   "price": "100000000"
}


####

POST http://localhost:5050/login HTTP/1.1
Content-Type: application/json

{
   "email": "orlaale@live.it",
   "password": "Vovinam2009"
}


####

PATCH http://localhost:5050/user/update/654793f40ee076ff8e428358
Content-Type: application/json

{
   "phoneNumber": 33366689
}


####

PATCH http://localhost:5050/company/update/654bc3e7b6f02f35c850eaf6
Content-Type: application/json

{
   "phoneNumber": 3336668999
}


####


DELETE http://localhost:5050/user/delete/654793f40ee076ff8e428358
####


DELETE http://localhost:5050/company/delete/654bc3e7b6f02f35c850eaf6